### ISSUE TITLE
App Crashes for Bigger Inputs

### ISSUE THREAD

**Issue by hardikchopra242** [Logan1x/Nucleotide-Sequence-generator#11]
### ISSUE

When the length of nucleotides is given with a larger number the app crashes.
**For Instance** : When the input is close to 100 million (sometimes 10 million), there will be the following error as shown in the attached image. 

![ISSUE](https://user-images.githubusercontent.com/67067955/101833156-90f6f380-3b5e-11eb-9172-2d5d804b724e.png)

## POSSIBLE SOLUTION
In the `def hello( )` function which is in the hello.py file  an if condition can be given which when the input is greater than a certain degree will give a notifying message to the user to give an input less than that number

_P.S. -- The exact degree after which the app crashes is somewhere near 10-100 million_

**Comment by Logan1x** [comment]
@hardikchopra242 Thanks for pointing it out. I never tested it for big numbers. Would you like to work on this issue?

**Comment by hardikchopra242** [comment]
@Logan1x Yes , I think I can do this.

**Comment by Logan1x** [comment]
Fixed in #13 .
