### ISSUE TITLE
Add a footer

### ISSUE THREAD

**Issue by Logan1x** [Logan1x/Nucleotide-Sequence-generator#4]
Can you add a footer with matching color scheme? If yes we need your help...

**Comment by Abhishekchauhan089** [comment]
I would like to work on this project

**Comment by Logan1x** [comment]
Sure go ahead. I'll assign it to you. @Abhishekchauhan089

**Comment by astha-garhewal** [comment]
@Logan1x Can I also work on this issue 😬?

**Comment by Logan1x** [comment]
@astha-garhewal We need to work on 404 error page a bit. If you want to work on that please look at #5

**Comment by Abhishekchauhan089** [comment]
@Logan1x i have made a PR for adding footer. check it out
