### ISSUE TITLE
About this project(Nuecleotide) page

### ISSUE THREAD

**Issue by tusshar17** [Logan1x/Nucleotide-Sequence-generator#6]
Hi @Logan1x , I would like to add **header** and an option where user can get to know _what is this project_ or in which **we can explain more about Nucleotide**

**Comment by Logan1x** [comment]
> an option where user can get to know what is this project or in which we can explain more about Nucleotide

Okay, for this make an HTML page with **same color scheme** and then **add routes in hello.py** file.

and header issue is taken.
